name: dvc-cml-miic
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-test
    steps:
      - uses: actions/checkout@v2
        
      - uses: r-lib/actions/setup-r@master
        with:
          version: '3.6.1'
      
      - name: Cache R packages
        uses: actions/cache@v1 
        with: 
          path: ${{ env.R_LIBS_USER }} 
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }} 
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1- 
           
      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: miic_R_package-1.4.2
          key: miic_R_package-1.4.2 
        
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # Install miic and dependencies
          R --silent -e "install.packages(c(\"igraph\", \"ppcor\", \"scales\", \"Rcpp\"))"
          
          MIIC_PACK=miic_R_package-1.4.2
          if [ ! -d $MIIC_PACK ]; then
            wget -c https://github.com/miicTeam/miic_R_package/archive/$MIIC_PACK
            tar -xvzf $MIIC_PACK
            cd $MIIC_PACK
            R CMD INSTALL . --preclean
            cd ..
          fi
          
          # Run DVC
          # dvc pull
          # Rscript infer_network.R
         
          # Write your CML report
          echo "## Model Metrics" > report.md
          # cat metrics.txt >> report.md
          # echo "## Data visualization" >> report.md
          # cml-publish network_diagram.png --md >> report.md
          cml-send-comment report.md
